name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/15 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto
        run: |
          git config --local user.email "dako@43rnb7.onmicrosoft.com"
          git config --local user.name "43rnb7"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Make Program Every Day!"
          git push
